# Generated by Django 5.2.17 on 2026-09-29 14:45

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Identificador del equipo (el antiguo ID de Firestore).",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("direccion", models.CharField(max_length=255)),
                (
                    "ubicacion",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "tipo_comunicacion",
                    models.CharField(
                        choices=[
                            ("Fibra óptica", "Fibra óptica"),
                            ("Celular", "Celular"),
                        ],
                        max_length=20,
                    ),
                ),
                ("piloto", models.CharField(blank=True, max_length=100)),
                ("fecha_fabricacion", models.DateField(blank=True, null=True)),
                ("fecha_ultima_revision", models.DateTimeField(blank=True, null=True)),
                ("revision_count", models.PositiveIntegerField(default=0)),
                ("requiere_canasta", models.BooleanField(default=False)),
                ("zona_peligrosa", models.BooleanField(default=False)),
                (
                    "proximo_mantenimiento_programado",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "intervalo_mantenimiento_dias",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "intervalo_mantenimiento_revisiones",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("campos_adicionales", models.JSONField(blank=True, default=dict)),
                (
                    "estado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equipos",
                        to="catalogs.estadoequipo",
                    ),
                ),
                (
                    "marca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equipos",
                        to="catalogs.marca",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equipos",
                        to="catalogs.tipoequipo",
                    ),
                ),
                (
                    "zona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equipos",
                        to="catalogs.zona",
                    ),
                ),
            ],
            options={
                "verbose_name": "equipo",
                "verbose_name_plural": "equipos",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="EquipoEstadoHistorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
                ("motivo", models.TextField(blank=True)),
                (
                    "equipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estado_historial",
                        to="assets.equipo",
                    ),
                ),
                (
                    "estado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalogs.estadoequipo",
                    ),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "cambio de estado de equipo",
                "verbose_name_plural": "historial de estados de equipos",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Identificador interno (el antiguo ID de Firestore).",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("placa", models.CharField(max_length=15, unique=True)),
                (
                    "custodio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehiculos_en_custodia",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "estado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehiculos",
                        to="catalogs.estadovehiculo",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehiculos",
                        to="catalogs.tipovehiculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "vehículo",
                "verbose_name_plural": "vehículos",
                "ordering": ["placa"],
            },
        ),
        migrations.AddIndex(
            model_name="equipo",
            index=models.Index(
                fields=["zona", "tipo"], name="assets_equi_zona_id_bc60b4_idx"
            ),
        ),
    ]
