# Generated by Django 5.2.17 on 2026-09-29 14:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mensaje", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("nueva_solicitud", "Nueva solicitud"),
                            ("solicitud_asignada", "Solicitud asignada"),
                            ("solicitud_cancelada", "Solicitud cancelada"),
                            ("nueva_ot", "Nueva orden de trabajo"),
                            ("trabajo_completado", "Trabajo completado"),
                            ("trabajo_no_completado", "Trabajo no completado"),
                            ("trabajo_revisado", "Trabajo revisado"),
                            ("trabajo_cancelado", "Trabajo cancelado"),
                            ("info_general", "Información general"),
                        ],
                        default="info_general",
                        max_length=30,
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("leida", models.BooleanField(default=False)),
                ("entidad_id", models.CharField(blank=True, max_length=60)),
                ("entidad_url", models.CharField(blank=True, max_length=255)),
                (
                    "creada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "notificación",
                "verbose_name_plural": "notificaciones",
                "ordering": ["-fecha_creacion"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "leida", "-fecha_creacion"],
                        name="notificatio_usuario_98eed8_idx",
                    )
                ],
            },
        ),
    ]
