# Generated by Django 5.2.17 on 2026-09-29 14:45

import apps.core.uploads
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0001_initial"),
        ("catalogs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdenDeTrabajo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "display_id",
                    models.CharField(editable=False, max_length=30, unique=True),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "estado_general",
                    models.CharField(
                        choices=[
                            ("Pendiente", "Pendiente"),
                            ("En Progreso", "En progreso"),
                            ("CompletadaParcial", "Completada parcialmente"),
                            ("CompletadaTotal", "Completada"),
                            ("Cancelada", "Cancelada"),
                        ],
                        default="Pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "firestore_id",
                    models.CharField(
                        blank=True, max_length=128, null=True, unique=True
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordenes_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "orden de trabajo",
                "verbose_name_plural": "órdenes de trabajo",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="OTUnidadAsignada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ruta_id", models.CharField(blank=True, max_length=60)),
                (
                    "orden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unidades_asignadas",
                        to="operations.ordendetrabajo",
                    ),
                ),
                (
                    "tecnicos",
                    models.ManyToManyField(
                        related_name="unidades_asignadas_ot",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asignaciones",
                        to="assets.vehiculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "unidad asignada",
                "verbose_name_plural": "unidades asignadas",
            },
        ),
        migrations.CreateModel(
            name="PlanMantenimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                ("nombre", models.CharField(max_length=150)),
                (
                    "fecha_creacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("tiempo_de_ejecucion_dias", models.PositiveIntegerField()),
                ("exclusiones", models.JSONField(blank=True, default=list)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("activo", "Activo"),
                            ("completado", "Completado"),
                            ("archivado", "Archivado"),
                        ],
                        default="borrador",
                        max_length=20,
                    ),
                ),
                ("estadisticas", models.JSONField(blank=True, default=dict)),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "plan de mantenimiento",
                "verbose_name_plural": "planes de mantenimiento",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="Solicitud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "display_id",
                    models.CharField(editable=False, max_length=30, unique=True),
                ),
                (
                    "fecha_solicitud",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("fecha_programada", models.DateField()),
                (
                    "tiempo_servicio_estimado",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="tiempo de servicio estimado (min)",
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("asignada", "Asignada"),
                            ("cancelada", "Cancelada"),
                            ("completada", "Completada"),
                            ("no_completada", "No completada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("motivo_cancelacion", models.TextField(blank=True)),
                (
                    "firestore_id",
                    models.CharField(
                        blank=True, max_length=128, null=True, unique=True
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solicitudes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solicitudes",
                        to="assets.equipo",
                    ),
                ),
                (
                    "tipo_trabajo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalogs.tipotrabajo",
                    ),
                ),
                (
                    "urgencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalogs.urgencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "solicitud",
                "verbose_name_plural": "solicitudes",
                "ordering": ["-fecha_solicitud"],
            },
        ),
        migrations.CreateModel(
            name="MantenimientoProgramado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_programada", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("programado", "Programado"),
                            ("solicitud_creada", "Solicitud creada"),
                            ("completado_ot", "Completado en OT"),
                        ],
                        default="programado",
                        max_length=20,
                    ),
                ),
                ("motivo_prioridad", models.TextField(blank=True)),
                (
                    "equipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="assets.equipo",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendario",
                        to="operations.planmantenimiento",
                    ),
                ),
                (
                    "solicitud",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="operations.solicitud",
                    ),
                ),
            ],
            options={
                "verbose_name": "mantenimiento programado",
                "verbose_name_plural": "mantenimientos programados",
                "ordering": ["fecha_programada"],
            },
        ),
        migrations.CreateModel(
            name="Trabajo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "codigo",
                    models.CharField(editable=False, max_length=40, unique=True),
                ),
                ("secuencia", models.PositiveSmallIntegerField(editable=False)),
                (
                    "tiempo_servicio_estimado",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Pendiente", "Pendiente"),
                            ("Completado", "Completado"),
                            ("No Completado", "No completado"),
                            ("Cancelado", "Cancelado"),
                        ],
                        default="Pendiente",
                        max_length=20,
                    ),
                ),
                ("detalles", models.TextField(blank=True)),
                ("hallazgos", models.TextField(blank=True)),
                ("fecha_finalizacion", models.DateTimeField(blank=True, null=True)),
                ("observacion_ingeniero", models.TextField(blank=True)),
                (
                    "fecha_observacion_ingeniero",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("requiere_nueva_revision", models.BooleanField(default=False)),
                ("fecha_nueva_revision", models.DateField(blank=True, null=True)),
                ("motivo_cancelacion", models.TextField(blank=True)),
                (
                    "completado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trabajos_completados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trabajos",
                        to="assets.equipo",
                    ),
                ),
                (
                    "observacion_ingeniero_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "orden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trabajos",
                        to="operations.ordendetrabajo",
                    ),
                ),
                (
                    "solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trabajos",
                        to="operations.solicitud",
                    ),
                ),
                (
                    "tipo_trabajo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalogs.tipotrabajo",
                    ),
                ),
            ],
            options={
                "verbose_name": "trabajo",
                "verbose_name_plural": "trabajos",
                "ordering": ["orden", "secuencia"],
            },
        ),
        migrations.CreateModel(
            name="TrabajoFoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        upload_to=apps.core.uploads.RutaAleatoria("trabajos/fotos")
                    ),
                ),
                ("subida_en", models.DateTimeField(auto_now_add=True)),
                (
                    "subida_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trabajo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotos",
                        to="operations.trabajo",
                    ),
                ),
            ],
            options={
                "verbose_name": "foto de trabajo",
                "verbose_name_plural": "fotos de trabajos",
                "ordering": ["subida_en"],
            },
        ),
        migrations.CreateModel(
            name="UnidadDeCampo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tecnicos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="unidades_de_campo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehiculo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unidad",
                        to="assets.vehiculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "unidad de campo",
                "verbose_name_plural": "unidades de campo",
            },
        ),
        migrations.AddIndex(
            model_name="solicitud",
            index=models.Index(
                fields=["estado", "fecha_programada"],
                name="operations__estado_6a9bc0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trabajo",
            index=models.Index(
                fields=["estado", "fecha_finalizacion"],
                name="operations__estado_214be1_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="trabajo",
            constraint=models.UniqueConstraint(
                fields=("orden", "secuencia"), name="trabajo_secuencia_unica"
            ),
        ),
    ]
