# Generated by Django 5.2.17 on 2026-09-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="planmantenimiento",
            name="firestore_id",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
