# Generated by Django 5.2.17 on 2026-09-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Secuencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prefijo", models.CharField(max_length=10)),
                ("fecha", models.DateField()),
                ("ultimo", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "secuencia",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("prefijo", "fecha"),
                        name="secuencia_prefijo_fecha_unica",
                    )
                ],
            },
        ),
    ]
