# Generated by Django 5.2.17 on 2026-09-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_habilidades_iniciales"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="debe_cambiar_password",
            field=models.BooleanField(
                default=False,
                help_text="Obliga a cambiar la contraseña (temporal) en el próximo inicio de sesión.",
                verbose_name="debe cambiar la contraseña",
            ),
        ),
    ]
