# Generated by Django 5.2.17 on 2026-09-29 14:45

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Configuracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empresa_nombre", models.CharField(blank=True, max_length=150)),
                (
                    "empresa_unidad_negocio",
                    models.CharField(blank=True, max_length=150),
                ),
                ("empresa_departamento", models.CharField(blank=True, max_length=150)),
                ("sede_central_nombre", models.CharField(blank=True, max_length=150)),
                (
                    "sede_central_ubicacion",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("hora_inicio_jornada", models.TimeField(blank=True, null=True)),
                ("hora_fin_jornada", models.TimeField(blank=True, null=True)),
                ("minutos_planificacion", models.PositiveIntegerField(default=0)),
                ("minutos_reporte", models.PositiveIntegerField(default=0)),
                ("minutos_almuerzo", models.PositiveIntegerField(default=60)),
                ("hora_inicio_almuerzo", models.TimeField(blank=True, null=True)),
                ("hora_fin_almuerzo", models.TimeField(blank=True, null=True)),
                (
                    "zona_horaria",
                    models.CharField(default="America/Guayaquil", max_length=64),
                ),
            ],
            options={
                "verbose_name": "configuración general",
            },
        ),
        migrations.CreateModel(
            name="EstadoEquipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.SlugField(
                        help_text="Identificador estable (no cambiar tras crear).",
                        max_length=60,
                        unique=True,
                    ),
                ),
                ("etiqueta", models.CharField(max_length=120)),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "estado de equipo",
                "verbose_name_plural": "estados de equipos",
                "ordering": ["orden", "etiqueta"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EstadoVehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.SlugField(
                        help_text="Identificador estable (no cambiar tras crear).",
                        max_length=60,
                        unique=True,
                    ),
                ),
                ("etiqueta", models.CharField(max_length=120)),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "estado de vehículo",
                "verbose_name_plural": "estados de vehículos",
                "ordering": ["orden", "etiqueta"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Localidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120, unique=True)),
                (
                    "ubicacion",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
            ],
            options={
                "verbose_name": "localidad",
                "verbose_name_plural": "localidades",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Marca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.SlugField(
                        help_text="Identificador estable (no cambiar tras crear).",
                        max_length=60,
                        unique=True,
                    ),
                ),
                ("etiqueta", models.CharField(max_length=120)),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "marca de equipo",
                "verbose_name_plural": "marcas de equipos",
                "ordering": ["orden", "etiqueta"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RespuestaPredefinida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.SlugField(
                        help_text="Identificador estable (no cambiar tras crear).",
                        max_length=60,
                        unique=True,
                    ),
                ),
                ("etiqueta", models.CharField(max_length=120)),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "respuesta predefinida",
                "verbose_name_plural": "respuestas predefinidas",
                "ordering": ["orden", "etiqueta"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TipoEquipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.SlugField(
                        help_text="Identificador estable (no cambiar tras crear).",
                        max_length=60,
                        unique=True,
                    ),
                ),
                ("etiqueta", models.CharField(max_length=120)),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "tipo de equipo",
                "verbose_name_plural": "tipos de equipos",
                "ordering": ["orden", "etiqueta"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TipoVehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.SlugField(
                        help_text="Identificador estable (no cambiar tras crear).",
                        max_length=60,
                        unique=True,
                    ),
                ),
                ("etiqueta", models.CharField(max_length=120)),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "tipo de vehículo",
                "verbose_name_plural": "tipos de vehículos",
                "ordering": ["orden", "etiqueta"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Urgencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.SlugField(
                        help_text="Identificador estable (no cambiar tras crear).",
                        max_length=60,
                        unique=True,
                    ),
                ),
                ("etiqueta", models.CharField(max_length=120)),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "urgencia",
                "verbose_name_plural": "urgencias",
                "ordering": ["orden", "etiqueta"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Zona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.SlugField(
                        help_text="Identificador estable (no cambiar tras crear).",
                        max_length=60,
                        unique=True,
                    ),
                ),
                ("etiqueta", models.CharField(max_length=120)),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "zona",
                "verbose_name_plural": "zonas",
                "ordering": ["orden", "etiqueta"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TipoTrabajo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("tiempo_estimado_minutos", models.PositiveIntegerField(default=30)),
                ("activo", models.BooleanField(default=True)),
                (
                    "tipo_equipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tipos_de_trabajo",
                        to="catalogs.tipoequipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "tipo de trabajo",
                "verbose_name_plural": "tipos de trabajo",
                "ordering": ["tipo_equipo", "nombre"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tipo_equipo", "nombre"),
                        name="tipotrabajo_unico_por_tipo_equipo",
                    )
                ],
            },
        ),
    ]
