# Generated by Django 5.2.17 on 2026-10-09 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0002_valores_iniciales"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configuracion",
            name="zona_horaria",
        ),
    ]
